### ISSUE TITLE
Shims are not resolved correctly when gentype project is compiled as a dependency

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#315] opened 2019-11-16 17:14 UTC
@cristianoc  following https://github.com/cristianoc/genType/issues/231#issuecomment-554655648

In monorepo projects if dependency is compiled from another package shims paths are not resolved correctly.
 
Can be reproduced here https://github.com/Coobaha/gentype-monorepo-issue

```
.

├── Demo.re
├── ToShim.re
└── shims
    └── Shimmed.shim.ts
```
>When compiled from main package.json packages/shim-demo/src/Demo.gen.tsx gets incorrect shim path:
import {t as ToShim_t} from './Shimmed.shim';
>
> When compiled from module itself path is correct:
import {t as ToShim_t} from '../src/shims/Shimmed.shim';

> Can you explain at a high level what you would expect to happen and the rational about it?

I expect that generated code will use same paths no matter when it is compiled as root or as dependency, currently gentype produces incorrect paths

**Comment by cristianoc** [comment] 2019-11-16 17:53
@Coobaha see the release notes: https://github.com/cristianoc/genType/releases/tag/v3.4.2.

In particular: "Note that dependent packages should be built first. If you rely on bucklescript to build them starting from the root package, it will not work as the required lib/bs/.sourcedirs.json will be missing). This will be addressed in a future version of bucklescript.".

I've added some debug printing to at least make one aware of what's going on:
https://github.com/cristianoc/genType/commit/25f86b4f93959f2ccb9b53f798df2d525f2116e9

**Comment by cristianoc** [comment] 2019-11-16 17:56
@Coobaha this is what needs to happen: https://github.com/BuckleScript/bucklescript/issues/3962.

**Comment by Coobaha** [comment] 2019-11-16 17:56
Ah I see, workaround for building root packages is to place shims in a root source folder. Might be worth to add it to release notes/readme

**Comment by cristianoc** [comment] 2019-11-16 17:59
@Coobaha the problem is not only shims. All cross-references are going to be problematic.

**Comment by cristianoc** [comment] 2019-11-19 09:26
@Coobaha one more PR for the remaining issue in your project: https://github.com/cristianoc/genType/pull/318.

**Comment by cristianoc** [comment] 2019-11-19 09:34
@Coobaha if this resolves the remaining issues, I will create a new release 3.4.3.

**Comment by cristianoc** [comment] 2019-11-19 17:06
New release created.

**Closed by cristianoc** 2019-11-19 17:06 UTC
