### ISSUE TITLE
genType.import of nested types causes name conflicts in TypeScript 3.7.2

### ISSUE THREAD

**Issue by wokalski** [cristianoc/genType#302] opened 2019-11-08 14:29 UTC
```ocaml
[@genType.import ("./MyMath", "num")]
type num;
```

Generates:

```typescript
import {num as num} from './MyMath';

// tslint:disable-next-line:interface-over-type-literal
export type num = num;
```

When you compile it with `tsc` you get:

```
Import declaration conflicts with local declaration of 't'.
```

**Comment by cristianoc** [comment] 2019-11-08 14:42
@wokalski why regression vs just an issue?

If you rename `t` in `type t = Js.Dict.t(tsunknown);` you don't get issues right? Making sure that's the issue.

**Comment by cristianoc** [comment] 2019-11-08 14:47
@wokalski 

Btw notice:
```
[@genType.import "something"]
type t = some_type_definition;
```
is not a useful pattern.
If the type is imported, then it's not checked against the local definition.

**Comment by cristianoc** [comment] 2019-11-08 14:49
I guess what we're looking at there is a feature request, where the above pattern is checked: there's the JS type definition, there's the Reason type definition, and one would like to check that they match.

And I guess match means something like: if the reason type `rt` maps to js type `toJS(rt)` when any value of type `jstype` defined in the JS file is also of type `toJS(rt)`.

**Comment by wokalski** [comment] 2019-11-08 14:50
Right @cristianoc. I figured it's better to use `external` and `%identity` in this case.

**Comment by wokalski** [comment] 2019-11-08 14:59
I'm closing this one. Seems like an interesting feature @cristianoc but it feels like an error is a desirable result now. Maybe it should even fail during `genType` execution!

**Comment by wokalski** [comment] 2019-11-08 15:30
Reopening:

```
[@genType.import ("./StyleSheet", "AnyStyleProp")]
type t;
```

compiles to:

```
/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {AnyStyleProp as t} from './StyleSheet';

// tslint:disable-next-line:interface-over-type-literal
export type t = t;
```

which causes the same error.

**Comment by cristianoc** [comment] 2019-11-08 15:46
@wokalski thanks it appears I have zero examples of that pattern, and needs to be fixed.
Thanks for spotting it!

**Comment by cristianoc** [comment] 2019-11-08 15:55
@wokalski I have added an example here: `https://github.com/cristianoc/genType/pull/303`.

I think that's what you want.
While the tuple argument of `@genType.import` is used to access classes inside the module.

I strongly suspect this is not exactly clear from the documentation.

**Comment by cristianoc** [comment] 2019-11-08 15:56
Maybe in the case of interfaces one does need that pattern?

**Comment by cristianoc** [comment] 2019-11-08 16:06
Here's a very simple problematic example:
```reason
[@genType.import ("./MyMath", "num")]
type num;
```
gives
```js
import {num as num} from './MyMath';

// tslint:disable-next-line:interface-over-type-literal
export type num = num;
```

**Comment by wokalski** [comment] 2019-11-08 16:15
Yes @cristianoc, exactly. Let me put this example in the issue description so that it's clear in the future what it's about.

**Comment by cristianoc** [comment] 2019-11-08 16:39
@wokalski I have added a few more examples here: https://github.com/cristianoc/genType/pull/303.
They all type check for me. Including the "problematic" one above.

**Comment by cristianoc** [comment] 2019-11-08 16:40
Maybe it's about choosing different example, or maybe it's about TS version and/or config.

**Comment by wokalski** [comment] 2019-11-08 16:56
hmm, it's probably the version! I just upgraded 🤦‍♀ 
Version 3.7.2

**Comment by cristianoc** [comment] 2019-11-08 18:18
@wokalski how did it go after version upgrade?

**Comment by wokalski** [comment] 2019-11-08 18:46
I had to downgrade and I think it builds correctly now.

**Comment by cristianoc** [comment] 2019-11-08 19:11
Closing optimistically.

**Comment by wokalski** [comment] 2019-11-08 19:39
I mean that the code generated by genType is incompatible with new versions of typescript! I think this requires a re-open 😄

**Comment by cristianoc** [comment] 2019-11-08 19:45
I can confirm repro on TS 3.7.2.

**Comment by cristianoc** [comment] 2019-11-08 20:17
An interesting aspect is that the error fire on old examples, and *not* on the new ones introduced for this issue. It looks pretty random.

**Comment by cristianoc** [comment] 2019-11-08 21:05
@wokalski fixed here: https://github.com/cristianoc/genType/pull/304

**Comment by wokalski** [comment] 2019-11-08 21:34
Great, thanks!

**Closed** 2019-11-09 03:07 UTC
